import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import { Footer } from "./components/Footer";
import ClientSettings from "./settings_client"; 
import { ThemeProvider } from "./components/ThemeProvider";
import "./globals.css";
import { useTranslation } from "@/lib/i18n";

config.autoAddCss = false;

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

// TO DO: META DATA
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.className} antialiased flex flex-col min-h-screen`}>
        <ThemeProvider>
          {children}
          <ClientSettings />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}